services:
  app:
    image: clothing-retail-product-service:latest
    container_name: clothing-retail-product-service
    restart: unless-stopped

    ports:
      - "9081:9081"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/clothing_retail_product
      DB_USERNAME: postgres
      DB_PASSWORD: password

      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: clothing-retail-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: clothing_retail_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5434:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clothing_retail_product"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: clothing-retail-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - product_redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  product_postgres_data:
  product_redis_data: